### ISSUE TITLE
Automatically run JS/SASS lint on commit

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/web-app#11]
Using git hooks. Is it possible to stop the commit if there's an issue?

**Comment by mitogh** [comment]
Don't think is needed make things more slower and we already have CI in place to prevent this.

**Comment by mitogh** [comment]
Probably it can be a personal preference but I'm not 100% sure of use it on my own development process. We can add it as optional if you like.

**Comment by adamf321** [comment]
It was just a thought so we don't forget to run CI locally, I know sometimes I do. Do you have a personal process in place to help with this @mitogh ?

**Comment by mitogh** [comment]
Ok…well yes I know that sometimes happen to me too but it can become more ugly if we force to run CI before every commit, I think the way we can avoid that is just to prevent directly write on master and develop and use PR to merge code on those branches so in that way we force to run the CI before moving something to those branches.  We can work to send a notification instead I think it would be more friendly.

**Comment by mitogh** [comment]
I think we should close this, since this is more like a personal preference.

**Comment by adamf321** [comment]
ok
