### ISSUE TITLE
Set-up dependency manager

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/web-app#2]
Browserify or WebPack.
Also the Gulp tasks required to watch and compile.

**Comment by adamf321** [comment]
Note the $templateCache outputs to `www/js/templates.js`

For now I've just included in index.html separately, but I guess you could bundle it up with Browserify.

**Comment by adamf321** [comment]
Can we make 2 separate bundles for - 1 for our code and 1 for any additional libs. I find it's quite slow to build with NPT now. We can also use external CDN's for Angular, ngRoute and jQuery like I've set up already.

**Comment by mitogh** [comment]
Browserify has been setup I'm going to create two builds scripts one for production and one for staging to improve speed. Watch has been added as well for js.
