### ISSUE TITLE
Speed up Travis builds

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/web-app#42]
**Steps to reproduce and a minimal demo of the problem**
Open a pull request

**Current behavior**
Travis builds take a few minutes to run

**Expected/desired behavior**
They run in seconds

**Other information**
This slows us down a lot. Eg when I have several PR's to review on a project I have to wait a few minutes between each one (as it forces you to update from develop each time).

Ideally we would find a way to make it much quicker. It's only required for checking Lint, so can we come up with a simplified build which only does this?

Also is there a way to make github only allow the merge if the checks have passed, but not force you to update from develop before merging?

**Comment by mitogh** [comment]
A couple of things on this one:
1. The thing is that travis run based on your type of account allow `n` number of concurrent jobs to run in parallel.
2. One of the things to speed things is to enable the cache,
3. Yes we can disable that on every repo.
