### ISSUE TITLE
Default WP styles

### ISSUE THREAD

**Issue by mitogh** [moxie-leean/web-app#44]
**Expected/desired behavior**

By default WP requires to use some styles on certain elements that rely on the editor.

Here is the complete list:

https://github.com/moxie-leean/Leean/blob/master/assets/sass/base/_wordpress.scss

Ideally this needs to be placed or required by the classes that output the information from the editor.

**Comment by adamf321** [comment]
Can we just add this scss file to the project and import it? It will be required by most projects I think.

**Comment by mitogh** [comment]
Well that how it works on the theme and that how is supposed to work here as well.
