### ISSUE TITLE
Improve JS Lint rules

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/web-app#48]
**Steps to reproduce and a minimal demo of the problem**
The rule set is not very complete

**Current behavior**
e.g. it allows if(..){ or f(..) { or f(..) 

**Expected/desired behavior**
A more complete ruleset.

**Other information**

**Comment by mitogh** [comment]
Can you provide a more descriptive example since `f` can be mean a function or an `if`.

Thank you.

**Comment by adamf321** [comment]
I meant "if", sorry. It's just and example though.
`if(..){ or if(..) { or if(..)`
