### ISSUE TITLE
Env vars

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/web-app#5]
Need a way to include env vars in the build for:
- [ ] Dev mode (use uncompressed scripts).
- [ ] API endpoint route.

**Comment by adamf321** [comment]
Env files set-up in Gulp. Need to output the vars into the compiled files when #2 is completed. We can use something like this:

```
.pipe(babel({optional: [
      'utility.inlineEnvironmentVariables'
    ]}))
```

See https://www.npmjs.com/package/gulp-env

**Comment by mitogh** [comment]
No need now is doing based on NPM scripts
