### ISSUE TITLE
Set-up SASS codesniffer

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/web-app#6]
@nacho87 has a gulp module to use.

**Comment by adamf321** [comment]
Added.

@mitogh what do we need to do to make it run in Travis when pushing to github?

**Comment by mitogh** [comment]
What rules are we following for this?

**Comment by mitogh** [comment]
I think we need to define the rules before.

**Comment by adamf321** [comment]
It's just using the defaults provided by the Gulp SASS Lint module for now. Agreed we'll need to update them as we work, same for the JS/Angular rules.

**Comment by nacho87** [comment]
@adamf321 @mitogh i add some basic rules for test and works ok
