### ISSUE TITLE
Disable ES2015 transpile on development mode

### ISSUE THREAD

**Issue by mitogh** [moxie-leean/web-app#79]
**Current behavior**

At the moment we are compiling the JS every time even on development mode, at the moment Google Chrome has support for almost all the features of the new version of JS.

**Expected/desired behavior**

For development there is no really a reason to compile to the JS using babel we should do the complication as a process just before the deployment to staging or production, this will help to increase the speed of debugging and writing code during development.

**Comment by adamf321** [comment]
Sounds reasonable. I just wonder if it's likely we will see any bugs in staging which we'll miss on local. Also what about Firefox, I think some people use that for dev in our team (eg Raul) and this is open source so we should definitely support dev in FF too?

**Comment by mitogh** [comment]
The main thing is make the compilation process optional so there is no required for generate the JS but the task or script is still going to be present so if anyone wants to test in an older browser can just compile the assets and we can specify this task always on deploy so we make it optional and everytime is only required we compile the JS.

Also Firefox has a pretty good support as well for ES2015.
